
DJAH_COMPONENT_PROCESSOR(transform)
DJAH_COMPONENT_PROCESSOR(fov)
DJAH_COMPONENT_PROCESSOR(visual_mesh)
DJAH_COMPONENT_PROCESSOR(texture)
DJAH_COMPONENT_PROCESSOR(uv_modifier)
DJAH_COMPONENT_PROCESSOR(action_map)
DJAH_COMPONENT_PROCESSOR(scene_node)