
GL_ENUM_PROCESSOR(BufferUsage, StreamDraw	, GL_STREAM_DRAW	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, StreamRead	, GL_STREAM_READ	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, StreamCopy	, GL_STREAM_COPY	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, StaticDraw	, GL_STATIC_DRAW	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, StaticRead	, GL_STATIC_READ	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, StaticCopy	, GL_STATIC_COPY	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, DynamicDraw	, GL_DYNAMIC_DRAW	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, DynamicRead	, GL_DYNAMIC_READ	, 0,0)
GL_ENUM_PROCESSOR(BufferUsage, DynamicCopy	, GL_DYNAMIC_COPY	, 0,0)